# Generated by Django 5.2.1 on 2025-05-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido_cliente', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono_cliente', models.CharField(max_length=20, unique=True, verbose_name='telefono')),
                ('correo_cliente', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('fecha_nacimiento_cliente', models.DateField(blank=True, null=True, verbose_name='fecha De Nacimiento')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
