# Generated by Django 5.2.1 on 2025-05-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(auto_created=True, db_column='idProducto', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('precio', models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
